SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_b = r_b;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_b = r_b;
SELECT sum(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(l_a) from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(l_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(r_a) from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(r_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a;
SELECT sum(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT sum(l_a) from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT sum(l_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT sum(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT sum(r_a) from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT sum(r_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a +1 = r_a;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_a +1 = r_a;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a +1 = r_a;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = 1 + r_a;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_a = 1 + r_a;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = 1 + r_a;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b -1 = 1 + r_b;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_b -1 = 1 + r_b;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_b -1 = 1 + r_b;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL AND l_a < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL AND r_a < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL AND l_c < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL AND r_c < 10 ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a < 10 ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL AND l_a < 10 ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a < 10 ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL AND r_a < 10 ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c < 10 ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL AND l_c < 10 ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c < 10 ;
-- SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL ;
SELECT SUM(l_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL AND r_c < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_c = r_c;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_c = r_c;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_c = r_c;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_d = r_d;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_c *2 = r_c;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_c *2 = r_c;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_c *2 = r_c;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_d = 2 * r_d;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_d = 2 * r_d;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_d = 2 * r_d;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_d *2 = 2 * r_d;
SELECT * from cider_hash_join_table_probe INNER JOIN cider_hash_join_table_hash ON l_d *2 = 2 * r_d;
SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_d *2 = 2 * r_d;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT * from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_c = r_c ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b OR l_b = 10 ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b AND l_b IS NOT NULL ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe LEFT JOIN cider_hash_join_table_hash ON l_a = r_a AND l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL AND l_a < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL AND r_a < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL AND l_c < 10 ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c < 10 ;
-- SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL ;
SELECT * from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL AND r_c < 10 ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a < 10 ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE l_a IS NOT NULL AND l_a < 10 ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a < 10 ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_a = r_a WHERE r_a IS NOT NULL AND r_a < 10 ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c < 10 ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE l_c IS NOT NULL AND l_c < 10 ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c < 10 ;
-- SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL ;
SELECT SUM(r_a) from cider_hash_join_table_probe JOIN cider_hash_join_table_hash ON l_b = r_b WHERE r_c IS NOT NULL AND r_c < 10 ;
