SELECT * FROM cider_filter_test_1;
SELECT * FROM cider_filter_test_1 where TRUE;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 < 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 > 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 = 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 <= 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 >= 77;
-- SELECT col_1 FROM cider_filter_test_2 WHERE col_1 <> 77;
-- SELECT col_1 FROM cider_filter_test_2 WHERE col_1 IS NULL;
-- SELECT col_1 FROM cider_filter_test_2 WHERE col_1 IS NOT NULL;
SELECT col_1 FROM cider_filter_test_2 WHERE TRUE;
SELECT col_1 FROM cider_filter_test_2 WHERE FALSE;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 = 2;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 > 2;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 <> 2;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 = 3;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 <= 3;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 <> 3;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 <= 3 AND 2 >= 1;
SELECT col_1 FROM cider_filter_test_2 WHERE 2 <= 3 OR 2 >= 1;
-- SELECT col_1 FROM cider_filter_test_2 WHERE 2 <= 3 AND col_1 <> 77;
-- SELECT col_1 FROM cider_filter_test_2 WHERE 2 = 3 OR col_1 <> 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 - 10 <= 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 + 10 >= 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 * 2 < 77;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 / 2 > 77;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 < 77;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 > 77;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 = 77;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 <= 77;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 >= 77;
-- SELECT col_2 FROM cider_filter_test_2 WHERE col_2 <> 77;
-- SELECT col_2 FROM cider_filter_test_2 WHERE col_2 IS NULL;
-- SELECT col_2 FROM cider_filter_test_2 WHERE col_2 IS NOT NULL;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 < 77;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 > 77;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 = 77;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 <= 77;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 >= 77;
-- SELECT col_3 FROM cider_filter_test_2 WHERE col_3 <> 77;
-- SELECT col_3 FROM cider_filter_test_2 WHERE col_3 IS NULL;
-- SELECT col_3 FROM cider_filter_test_2 WHERE col_3 IS NOT NULL;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 < 77;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 > 77;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 = 77;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 <= 77;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 >= 77;
-- SELECT col_4 FROM cider_filter_test_2 WHERE col_4 <> 77;
-- SELECT col_4 FROM cider_filter_test_2 WHERE col_4 IS NULL;
-- SELECT col_4 FROM cider_filter_test_2 WHERE col_4 IS NOT NULL;
-- SELECT col_1 FROM cider_filter_test_2 WHERE col_1 > 50 or col_1 < 5;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 IS NULL or col_1 < 5;
-- SELECT col_2 FROM cider_filter_test_2 WHERE col_2 > 50 or col_2 < 5;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 IS NULL or col_2 < 5;
-- SELECT col_3 FROM cider_filter_test_2 WHERE col_3 > 50 or col_3 < 5;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 IS NULL or col_3 < 5;
-- SELECT col_4 FROM cider_filter_test_2 WHERE col_4 > 50 or col_4 < 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 IS NULL or col_4 < 5;
SELECT col_1 FROM cider_filter_test_2 WHERE col_1 < 50 and col_1 > 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_1 IS NOT NULL and col_1 > 5;
SELECT col_2 FROM cider_filter_test_2 WHERE col_2 < 50 and col_2 > 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_2 IS NOT NULL and col_2 > 5;
SELECT col_3 FROM cider_filter_test_2 WHERE col_3 < 50 and col_3 > 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_3 IS NOT NULL and col_3 > 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 < 50 and col_4 > 5;
SELECT col_4 FROM cider_filter_test_2 WHERE col_4 IS NOT NULL and col_4 > 5;
SELECT col_1, col_2 FROM cider_filter_test_2 WHERE col_1 = col_2;
SELECT col_2, col_3 FROM cider_filter_test_2 WHERE col_2 = col_3;
SELECT col_2, col_4 FROM cider_filter_test_2 WHERE col_2 = col_4;
SELECT col_3, col_4 FROM cider_filter_test_2 WHERE col_3 = col_4;
SELECT col_1, col_5 FROM cider_filter_test_3 WHERE col_1 < col_5;
SELECT col_2, col_6 FROM cider_filter_test_3 WHERE col_2 < col_6;
SELECT col_3, col_7 FROM cider_filter_test_3 WHERE col_3 <= col_7;
SELECT col_4, col_8 FROM cider_filter_test_3 WHERE col_4 <= col_8;
SELECT col_1, col_5 FROM cider_filter_test_3 WHERE col_1 <> col_5;
SELECT col_1, col_2, col_3, col_4 FROM cider_filter_test_3 WHERE col_2 <= col_3 and col_2 >= col_1;
SELECT col_1, col_2, col_3 FROM cider_filter_test_3 WHERE col_2 >= col_3 or col_2 <= col_1;
SELECT col_1, col_5 FROM cider_filter_test_3 WHERE col_1 < col_5 AND col_5 > 0;
-- SELECT * FROM cider_filter_test_3 WHERE (col_1 > 0 AND col_2 < 0) OR (col_1 < 0 AND col_2 > 0);
SELECT * FROM cider_filter_test_3 WHERE col_1 between 0 AND 1000 ;
SELECT col_1 FROM cider_filter_test_4 WHERE col_1 < 77;
SELECT col_2 FROM cider_filter_test_4 WHERE col_2 > 77;
SELECT col_3 FROM cider_filter_test_4 WHERE col_3 <= 77;
SELECT col_4 FROM cider_filter_test_4 WHERE col_4 >= 77;
SELECT col_1 FROM cider_filter_test_4 WHERE col_1 IS NOT NULL AND col_1 < 77;
SELECT col_2 FROM cider_filter_test_4 WHERE col_2 IS NOT NULL AND col_2 > 77;
SELECT col_3 FROM cider_filter_test_4 WHERE col_3 IS NOT NULL AND col_3 <= 77;
SELECT col_4 FROM cider_filter_test_4 WHERE col_4 IS NOT NULL AND col_4 >= 77;
