-- SELECT true FROM cider_constant_query_test;
-- SELECT 1 FROM cider_constant_query_test;
-- SELECT true FROM cider_constant_query_test where col_a > 10;
SELECT true, col_b FROM cider_constant_query_test where col_a > 10;
-- SELECT 3 < 2 FROM cider_constant_query_test;
-- SELECT 3 > 2 FROM cider_constant_query_test;
-- SELECT 3 = 2 FROM cider_constant_query_test;
-- SELECT 3 <= 2 FROM cider_constant_query_test;
-- SELECT 3 >= 2 FROM cider_constant_query_test;
-- SELECT 3 <> 2 FROM cider_constant_query_test;
-- SELECT CAST(null AS boolean) FROM cider_constant_query_test;
-- SELECT NOT CAST(null AS boolean) FROM cider_constant_query_test;
-- SELECT CAST(null AS boolean) AND true FROM cider_constant_query_test;
-- SELECT CAST(null AS boolean) AND false FROM cider_constant_query_test;
-- SELECT CAST(null AS boolean) OR true FROM cider_constant_query_test;
-- SELECT CAST(null AS boolean) OR false FROM cider_constant_query_test;
-- SELECT null and true FROM cider_constant_query_test;
-- SELECT null and false FROM cider_constant_query_test;
-- SELECT null or true FROM cider_constant_query_test;
-- SELECT null or false FROM cider_constant_query_test;
SELECT col_a = 2 AND col_b > 10 FROM cider_constant_query_test;
SELECT col_a = 2 OR col_b > 10 FROM cider_constant_query_test;
