SELECT * FROM primitive_type_query_test_1;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_1;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_1;
SELECT col_b, col_c FROM primitive_type_query_test_1;
SELECT col_b, col_a FROM primitive_type_query_test_1;
SELECT col_a FROM primitive_type_query_test_1;
SELECT col_b FROM primitive_type_query_test_1;
SELECT col_c FROM primitive_type_query_test_1;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_2;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_2;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_2;
SELECT col_b, col_c FROM primitive_type_query_test_2;
SELECT col_b, col_a FROM primitive_type_query_test_2;
SELECT col_a FROM primitive_type_query_test_2;
SELECT col_b FROM primitive_type_query_test_2;
SELECT col_c FROM primitive_type_query_test_2;
SELECT * FROM primitive_type_query_test_3;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_3;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_3;
SELECT col_b, col_c FROM primitive_type_query_test_3;
SELECT col_b, col_a FROM primitive_type_query_test_3;
SELECT col_a FROM primitive_type_query_test_3;
SELECT col_b FROM primitive_type_query_test_3;
SELECT col_c FROM primitive_type_query_test_3;
SELECT * FROM primitive_type_query_test_3;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_3;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_3;
SELECT col_b, col_c FROM primitive_type_query_test_3;
SELECT col_b, col_a FROM primitive_type_query_test_3;
SELECT col_a FROM primitive_type_query_test_3;
SELECT col_b FROM primitive_type_query_test_3;
SELECT col_c FROM primitive_type_query_test_3;
SELECT * FROM primitive_type_query_test_4;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_4;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_4;
SELECT col_b, col_c FROM primitive_type_query_test_4;
SELECT col_b, col_a FROM primitive_type_query_test_4;
SELECT col_a FROM primitive_type_query_test_4;
SELECT col_b FROM primitive_type_query_test_4;
SELECT col_c FROM primitive_type_query_test_4;
SELECT * FROM primitive_type_query_test_4;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_4;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_4;
SELECT col_b, col_c FROM primitive_type_query_test_4;
SELECT col_b, col_a FROM primitive_type_query_test_4;
SELECT col_a FROM primitive_type_query_test_4;
SELECT col_b FROM primitive_type_query_test_4;
SELECT col_c FROM primitive_type_query_test_4;
SELECT * FROM primitive_type_query_test_5;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_5;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_5;
SELECT col_b, col_c FROM primitive_type_query_test_5;
SELECT col_b, col_a FROM primitive_type_query_test_5;
SELECT col_a FROM primitive_type_query_test_5;
SELECT col_b FROM primitive_type_query_test_5;
SELECT col_c FROM primitive_type_query_test_5;
SELECT * FROM primitive_type_query_test_5;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_5;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_5;
SELECT col_b, col_c FROM primitive_type_query_test_5;
SELECT col_b, col_a FROM primitive_type_query_test_5;
SELECT col_a FROM primitive_type_query_test_5;
SELECT col_b FROM primitive_type_query_test_5;
SELECT col_c FROM primitive_type_query_test_5;
SELECT * FROM primitive_type_query_test_6;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_6;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_6;
SELECT col_b, col_c FROM primitive_type_query_test_6;
SELECT col_b, col_a FROM primitive_type_query_test_6;
SELECT col_a FROM primitive_type_query_test_6;
SELECT col_b FROM primitive_type_query_test_6;
SELECT col_c FROM primitive_type_query_test_6;
SELECT * FROM primitive_type_query_test_6;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_6;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_6;
SELECT col_b, col_c FROM primitive_type_query_test_6;
SELECT col_b, col_a FROM primitive_type_query_test_6;
SELECT col_a FROM primitive_type_query_test_6;
SELECT col_b FROM primitive_type_query_test_6;
SELECT col_c FROM primitive_type_query_test_6;
SELECT * FROM primitive_type_query_test_7;
SELECT col_a, col_b, col_c FROM primitive_type_query_test_7;
SELECT col_c, col_b, col_a FROM primitive_type_query_test_7;
SELECT col_b, col_c FROM primitive_type_query_test_7;
SELECT col_b, col_a FROM primitive_type_query_test_7;
SELECT col_a FROM primitive_type_query_test_7;
SELECT col_b FROM primitive_type_query_test_7;
SELECT col_c FROM primitive_type_query_test_7;
