-- SELECT c0 FROM scalar_func_expr_test_1 WHERE c0 between 0 and 5;
-- SELECT c0 FROM scalar_func_expr_test_1 WHERE c0 between 0 and 5;
-- SELECT c0 FROM scalar_func_expr_test_2 WHERE c0 between 0 and 5;
-- SELECT c0 FROM scalar_func_expr_test_2 WHERE c0 between 0 and 5;
SELECT c0 FROM scalar_func_expr_test_3 WHERE c0 between 0 and 5;
SELECT c0 FROM scalar_func_expr_test_3 WHERE c0 between 0 and 5;
SELECT c0 FROM scalar_func_expr_test_4 WHERE c0 between 0 and 5;
SELECT c0 FROM scalar_func_expr_test_4 WHERE c0 between 0 and 5;
SELECT c0 FROM scalar_func_expr_test_5 WHERE c0 between 0.0 and 5.0;
SELECT c0 FROM scalar_func_expr_test_5 WHERE c0 between 0.0 and 5.0;
SELECT c0 FROM scalar_func_expr_test_5 WHERE c0 between 0.0 and 5.0;
SELECT c0 FROM scalar_func_expr_test_5 WHERE c0 between 0.0 and 5.0;
