SELECT * FROM simple_cider_test;
SELECT col_a FROM simple_cider_test;
SELECT col_b FROM simple_cider_test;
SELECT col_a, col_b FROM simple_cider_test;
SELECT col_b, col_a FROM simple_cider_test;
-- SELECT * FROM simple_cider_test WHERE col_a IS NULL;
-- SELECT * FROM simple_cider_test WHERE col_b IS NOT NULL;
-- SELECT col_a, col_b, col_c FROM simple_cider_test WHERE col_a IS NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_a IS NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_a IS NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_c IS NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_c IS NULL;
-- SELECT col_a, col_b, col_c FROM simple_cider_test WHERE col_b IS NOT NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NOT NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_a IS NOT NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_b IS NOT NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_b IS NOT NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_b IS NOT NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_c IS NOT NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_c IS NOT NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NOT NULL;
-- SELECT col_a FROM simple_cider_test WHERE col_a IS NOT NULL AND col_c IS NOT NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NOT NULL;
-- SELECT col_b FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_a IS NULL AND col_c IS NOT NULL;
-- SELECT col_c FROM simple_cider_test WHERE col_a IS NOT NULL AND col_c IS NOT NULL;
SELECT col_a FROM simple_cider_test WHERE col_a IS NULL OR col_c IS NULL;
SELECT col_a FROM simple_cider_test WHERE col_a IS NULL OR col_c IS NOT NULL;
SELECT col_a FROM simple_cider_test WHERE col_a IS NOT NULL OR col_c IS NOT NULL;
SELECT col_c FROM simple_cider_test WHERE col_a IS NULL OR col_c IS NULL;
SELECT col_c FROM simple_cider_test WHERE col_a IS NULL OR col_c IS NOT NULL;
SELECT col_c FROM simple_cider_test WHERE col_a IS NOT NULL OR col_c IS NOT NULL;
-- SELECT * FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NULL AND col_c IS NULL;
-- SELECT * FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NULL AND col_c IS NOT NULL;
-- SELECT * FROM simple_cider_test WHERE col_a IS NULL AND col_b IS NOT NULL AND col_c IS NOT NULL;
-- SELECT * FROM simple_cider_test WHERE col_a IS NOT NULL AND col_b IS NOT NULL AND col_c IS NOT NULL;
