# Copyright(c) 2022-2023 Intel Corporation.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM ubuntu:20.04

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update \
    && apt-get install -y \
        tzdata \
        software-properties-common \
        build-essential \
        autoconf \
        automake \
        autoconf-archive \
        ninja-build \
        bison \
        flex \
        pkg-config \
        libtool \
        patch \
        patchelf \
        gdb \
        sudo \
        git \
        wget \
        unzip \
        vim \
        curl \
        openjdk-8-jdk \
        swig \
        libedit-dev \
        libdouble-conversion-dev \
        libre2-dev \
        uuid-dev \
        libsodium-dev \
        gperf \
        libssl-dev \
        python-dev \
        libevent-dev \
        zlib1g-dev \
        liblz4-dev \
        libsnappy-dev \
        libzstd-dev \
        libbz2-dev \
        liblzo2-dev \
        nasm \
    && apt-get remove --purge -y \
    && rm -rf /var/lib/apt/lists/*

ARG CMAKE_VERSION=3.17.0
RUN mkdir /opt/cmake-${CMAKE_VERSION}
RUN wget -nv -O - https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz | \
    tar -xzf - --strip-components=1 -C /opt/cmake-${CMAKE_VERSION}
ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:$PATH

ARG MAVEN_VERSION=3.6.3
RUN mkdir /opt/maven-${MAVEN_VERSION}
RUN wget -nv -O - https://mirrors.bfsu.edu.cn/apache/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | \
    tar -xzf - --strip-components=1 -C /opt/maven-${MAVEN_VERSION}
ENV PATH=/opt/maven-${MAVEN_VERSION}/bin:$PATH

ENV ISTHMUS_EXEC=/opt/substrait-java/isthmus/build/graal/isthmus

COPY install.sh /tmp
COPY llvm-9-glibc-2.31-708430-remove-cyclades.patch /tmp
RUN chmod a+x /tmp/install.sh && /tmp/install.sh && rm -rf /tmp/install.sh /tmp/llvm-9-glibc-2.31-708430-remove-cyclades.patch

WORKDIR /WorkSpace

ENTRYPOINT ["/bin/bash"]
