include(ExternalProject)

set(SUBSTRAITCPP_ROOT         ${CMAKE_BINARY_DIR}/thirdparty/SUBSTRAITCPP)
set(SUBSTRAITCPP_GIT_TAG      717bb017576536b5e970fa5bd06f1c3d51fa8939)
set(SUBSTRAITCPP_GIT_URL      https://github.com/substrait-io/substrait-cpp.git)
set(SUBSTRAITCPP_CONFIGURE    cd ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP && cmake -D CMAKE_POSITION_INDEPENDENT_CODE=ON && cmake -D CMAKE_INSTALL_PREFIX=${SUBSTRAITCPP_ROOT} .)
set(SUBSTRAITCPP_MAKE         cd ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP && make)
set(SUBSTRAITCPP_INSTALL      cd ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP && make install)
set(SUBSTRAITCPP_FUNCTION_LIB ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP/substrait/function/libsubstrait_function.a)
set(SUBSTRAITCPP_TYPE_LIB     ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP/substrait/type/libsubstrait_type.a)
set(SUBSTRAITCPP_COMMON_LIB   ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP/substrait/common/libsubstrait_common.a)
set(SUBSTRAITCPP_LIB_DIR      ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP/substrait)
set(SUBSTRAITCPP_INCLUDE_DIR  ${SUBSTRAITCPP_ROOT}/src/SUBSTRAITCPP/include)

find_path(LIBSUBSTRAITCPP_INCLUDE_DIR substrait ${SUBSTRAITCPP_INCLUDE_DIR})
find_library(LIBSUBSTRAITCPP_FUNCTION_LIB libsubstrait_function.a ${SUBSTRAITCPP_LIB_DIR})
find_library(LIBSUBSTRAITCPP_TYPE_LIB libsubstrait_type.a ${SUBSTRAITCPP_LIB_DIR})
if(NOT LIBSUBSTRAITCPP_INCLUDE_DIR
   OR NOT LIBSUBSTRAITCPP_FUNCTION_LIB
   OR NOT LIBSUBSTRAITCPP_TYPE_LIB)
  ExternalProject_Add(SUBSTRAITCPP
          PREFIX            ${SUBSTRAITCPP_ROOT}
          GIT_REPOSITORY    ${SUBSTRAITCPP_GIT_URL}
          GIT_TAG           ${SUBSTRAITCPP_GIT_TAG}
          CONFIGURE_COMMAND ${SUBSTRAITCPP_CONFIGURE}
          BUILD_COMMAND     ${SUBSTRAITCPP_MAKE}
          INSTALL_COMMAND   ${SUBSTRAITCPP_INSTALL}
  )
endif()
