-- Copyright (c) 2022 Intel Corporation.
--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- TPC-H/TPC-R Promotion Effect Query (Q14)
-- Functional Query Definition
-- Approved February 1998
-- select
-- 	100.00 * sum(case
-- 		when p.type like 'PROMO%'
-- 			then l.extendedprice * (1 - l.discount)
-- 		else 0
-- 	end) / sum(l.extendedprice * (1 - l.discount)) as promo_revenue
-- from
-- 	lineitem as l,
-- 	part as p
-- where
-- 	l.partkey = p.partkey
-- 	and l.shipdate >= date '1995-09-01'
-- 	and l.shipdate < date '1995-09-01' + interval '1' month;
