-- Copyright (c) 2022 Intel Corporation.
--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- TPC-H/TPC-R Small-Quantity-Order Revenue Query (Q17)
-- Functional Query Definition
-- Approved February 1998
-- select
-- 	sum(l.extendedprice) / 7.0 as avg_yearly
-- from
-- 	lineitem as l,
-- 	part as p
-- where
-- 	p.partkey = l.partkey
-- 	and p.brand = 'Brand#23'
-- 	and p.container = 'MED BOX'
-- 	and l.quantity < (
-- 		select
-- 			0.2 * avg(quantity)
-- 		from
-- 			lineitem
-- 		where
-- 			partkey = p.partkey
-- 	);
